apiVersion: v1
kind: Pod       #run a container
metadata: 
  name: client-pod  # name of pod
  labels:
    component: web  #This label is used by Service 
spec:
  containers:
    - name: client 
      image: smadaan2/multi-client
      ports:
        - containerPort: 3000   