apiVersion: v1
kind: Pod       #run a container
metadata: 
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client 
      image: smadaan2/multi-client
      ports:
        - containerPort: 3000   